name: misterio_no_campus
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.1.0        # mudou de ^13.0.0 para ^11.1.0
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/bg.jpg

  fonts:
    - family: RPG
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf

  uses-material-design: true